- name: Install semaphore
  hosts: me
  gather_facts: true

  tasks:
    - name: Update and upgrade apt packages
      ansible.builtinapt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
