---
- name: Install semaphore
  hosts: test
  gather_facts: true
  remote_user: root
  ansible_user: root

  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
